# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quota_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'quota_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13quota_service.proto\x12\rquota_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n\x04Tick\x12\x14\n\x0creceive_time\x18\x01 \x01(\x01\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08\x65xchange\x18\x03 \x01(\t\x12\x13\n\x0bmarket_type\x18\x04 \x01(\t\x12\x13\n\x0b\x62\x65st_bid_px\x18\x05 \x01(\x01\x12\x13\n\x0b\x62\x65st_bid_sz\x18\x06 \x01(\x01\x12\x13\n\x0b\x62\x65st_ask_px\x18\x07 \x01(\x01\x12\x13\n\x0b\x62\x65st_ask_sz\x18\x08 \x01(\x01\x12\x0f\n\x07\x62ids_px\x18\t \x03(\x01\x12\x0f\n\x07\x62ids_sz\x18\n \x03(\x01\x12\x0f\n\x07\x61sks_px\x18\x0b \x03(\x01\x12\x0f\n\x07\x61sks_sz\x18\x0c \x03(\x01\"6\n\x11IngestTickRequest\x12!\n\x04tick\x18\x01 \x01(\x0b\x32\x13.quota_service.Tick\"6\n\x12IngestTickResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x12IngestTicksRequest\x12\"\n\x05ticks\x18\x01 \x03(\x0b\x32\x13.quota_service.Tick\"P\n\x13IngestTicksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0fprocessed_count\x18\x03 \x01(\x05\"\x14\n\x12HealthCheckRequest\"J\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x8d\x02\n\x0cQuotaService\x12Q\n\nIngestTick\x12 .quota_service.IngestTickRequest\x1a!.quota_service.IngestTickResponse\x12T\n\x0bIngestTicks\x12!.quota_service.IngestTicksRequest\x1a\".quota_service.IngestTicksResponse\x12T\n\x0bHealthCheck\x12!.quota_service.HealthCheckRequest\x1a\".quota_service.HealthCheckResponseB2Z0github.com/bryanchen463/quota_data_service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quota_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/bryanchen463/quota_data_service/proto'
  _globals['_TICK']._serialized_start=72
  _globals['_TICK']._serialized_end=307
  _globals['_INGESTTICKREQUEST']._serialized_start=309
  _globals['_INGESTTICKREQUEST']._serialized_end=363
  _globals['_INGESTTICKRESPONSE']._serialized_start=365
  _globals['_INGESTTICKRESPONSE']._serialized_end=419
  _globals['_INGESTTICKSREQUEST']._serialized_start=421
  _globals['_INGESTTICKSREQUEST']._serialized_end=477
  _globals['_INGESTTICKSRESPONSE']._serialized_start=479
  _globals['_INGESTTICKSRESPONSE']._serialized_end=559
  _globals['_HEALTHCHECKREQUEST']._serialized_start=561
  _globals['_HEALTHCHECKREQUEST']._serialized_end=581
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=583
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=657
  _globals['_QUOTASERVICE']._serialized_start=660
  _globals['_QUOTASERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
